### ISSUE TITLE
slide width bug when upgrading to 0.14

### ISSUE THREAD

**Issue by aribronstein** [akiran/react-slick#465] opened 2016-09-08 08:44 UTC
I upgraded to 0.14 on my development environment today and my slides started getting very large width values and not showing multiple slides at once.

my settings:
```
settings = {
      dots: false,
      infinite: false,
      speed: 500,
      slidesToShow: 6,
      slidesToScroll: 6,
      waitForAnimate: false,
      // Resolutions
      responsive: [{
        breakpoint: 1510,
        settings: {
          slidesToShow: 6,
          slidesToScroll: 6
        }
      }, {
        breakpoint: 1025,
        settings: {
          slidesToShow: 4,
          slidesToScroll: 4
        }
      }, {
        breakpoint: 610,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 3
        }
      }, {
        breakpoint: 480,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2
        }
      }, {
        breakpoint: 321,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2
        }
      }]
    };
```

**Comment by ryanjoyceuk** [comment] 2016-09-08 12:37
Out of curiosity, are you using display:flex on any of the parent nodes are you? I'm trying to constrain the aspect ratio of a div within a flexbox'd node and then embedding the slider into that and experiencing the giant images. 

Ignoring the recalculation badtimes i've got screen resize, it feels like something isn't able to correctly calculate it's width - if i hard code px values it all works fine, but that kinda defeats the point of what i'm trying to do!

**Comment by aribronstein** [comment] 2016-09-08 12:43
I'm using Bootstrap 3 so the slide elements are each a percentage width in the css I am not using flex in connection to slick.
I am using flex in an sibling to the slider but less relevant.

**Comment by akiran** [comment] 2016-09-08 13:27
If you are using flex property, add the below in your css
```
* {
  min-height: 0;
  min-width: 0;
}
```

**Comment by akiran** [comment] 2016-09-08 17:02
I couldn't replicate this issue with the given settings 

Can you replicate this issue with jsfiddle
https://jsfiddle.net/kirana/20bumb4g/

**Comment by aribronstein** [comment] 2016-09-08 17:34
Here is the problem reproduced it might need a resize of the preview pane to trigger
https://jsfiddle.net/9sw8hqoo/

**Comment by creatifyme** [comment] 2016-09-08 17:55
@akiran I am also seeing this issue. I cloned your example and changed it to 2 slides to show.

Reproduceable steps:
- https://jsfiddle.net/creatifyme/20bumb4g/1245/
- resize the rendered slider panel width 
- example http://i.imgur.com/cvagDL8.gifv

**Comment by BenBarber** [comment] 2016-09-08 18:56
Im getting the same issue after updating, it was working perfect before 0.14. If it helps I have the slider in a column using React Flexbox Grid and have tried adding the CSS as mentioned by @akiran but that didn't make any difference for me.

**Comment by bradbirnbaum** [comment] 2016-09-08 19:18
I am also seeing the same issue.   On scroll in a parent div the translation calculation I am seeing some really interesting numbers. 
<img width="1119" alt="screen shot 2016-09-08 at 3 18 14 pm" src="https://cloud.githubusercontent.com/assets/97888/18363307/83701454-75d7-11e6-9a8d-fe15526193f4.png">

**Comment by akiran** [comment] 2016-09-09 13:47
@Josh-ES People started facing some issues after we merged vertical PR
Do you have any insights ?

**Comment by Josh-ES** [comment] 2016-09-09 14:56
@akiran I have a rough idea of what might be causing this, I'll investigate further and submit a pull request in a few. Bear with me!

**Closed** 2016-09-11 11:22 UTC

**Comment by akiran** [comment] 2016-09-11 11:28
Can you text out 0.14.2

**Comment by aribronstein** [comment] 2016-09-11 11:38
looks great, thanks!

**Comment by MakarovAV** [comment] 2016-11-30 14:49
Broken for me at the moment (0.14.5)

**Comment by giladbr** [comment] 2017-02-05 13:04
It seems it's a bug they didn't finish fixing. Here's a workaround that works for me - add the following to React's component that contains the react-slick:

  ```
  constructor() {
        [...]
        this.onWindowResized = this.onWindowResized.bind(this);
    }

    componentDidMount() {
        window.addEventListener('resize', this.onWindowResized);
    }


    componentWillUnmount () {
        window.removeEventListener('resize', this.onWindowResized);
    }

    onWindowResized() { //add debounce for performance?
        this.forceUpdate(); //react's default forceUpdate
    }
```

This will effectively force React to re-render the entire component on window resize, fixing the problem.
* The credit goes to the user [@iandoe](https://github.com/iandoe ) that [wrote about it](https://github.com/akiran/react-slick/issues/67) a year and a half ago...

**Comment by trekinbami** [comment] 2017-02-10 13:04
+1 - The demo and my own code completely break on a resize.

**Comment by uragecz** [comment] 2019-03-18 13:26
^0.23.2 and still broken.. content is constantly growing

**Comment by uragecz** [comment] 2019-03-18 13:27
UPDATE: it can't be surrounded by flex.. When i removed flex around now it works

**Comment by magiclinks-cpark** [comment] 2021-08-09 21:59
This is still happening. Any updates on fixes or workarounds for this problem? My slider is inside of a div element with a box display but the parent of this div element has display flex set. The flex is breaking the slider.
