### ISSUE TITLE
Empty <div> for each slide mandatory?

### ISSUE THREAD

**Issue by ghost** [akiran/react-slick#1818] opened 2020-06-05 12:18 UTC
I am using the Slider in combination with [Bulma](https://bulma.io/) which is a CSS framework that works pretty much like bootstrap.

I am trying to place an image next to some text per slide which looks like that:

```
<Slider {...settings}>
  <div>
    <Columns>
      <Columns.Column size={6}>
        some content
      </Columns.Column>
       ...
    </Columns>
  </div>
</Slider
```

If I write it like that it works perfectly fine but if I get rid of the empty div it ignores the columns. Do I always need an empty div to "start a slide"? It looks like that in the docs but the examples shown are also very easy so it's hard to tell if it's a must to wrap an empty div around the slide.

**Comment by gautamgoshopmatic** [comment] 2020-07-04 21:24
@mzdeloitte when you inspect element in the browser what does 

`
<Columns>
      <Columns.Column size={6}>
        some content
      </Columns.Column>
       ...
</Columns>
`

Transform to ?

does the outer most html element have css applied to it ? i guess it does maybe in which case its just better to use a html element without preexisting css applied to it. you can use a span instead of a div and it would be fine too. 

if you don't want to have the external div , see see what the html of bulma transpiles to and then you can have something like:

`
<div class='row'>
      <Columns.Column size={6}>
        some content
      </Columns.Column>
       ...
</div> 
`

see if this works.

**Comment by akiran** [comment] 2024-01-19 07:51
duplicate of #1877

**Closed by akiran** 2024-01-19 07:51 UTC
