### ISSUE TITLE
Importing the Slider component causes Mocha tests to fail

### ISSUE THREAD

**Issue by alexjhannan** [akiran/react-slick#348] opened 2016-07-01 14:16 UTC
I'm building unit tests for a React project right now, and upon importing a component that uses the Slider, this message is spat back out:

```
error: uncaughtException: matchMedia not present, legacy browsers require a polyfill date=Fri Jul 01 2016 10:10:47 GMT-0400 (EDT), pid=69405, uid=501, gid=20, cwd={...}/web, execPath=/usr/local/bin/node, version=v5.2.0, argv=[/usr/local/bin/node, {...}/web/node_modules/mocha/bin/_mocha, --require, test/utils/dom.js, --compilers, js:babel-core/register, test/containers/ActionBar.spec.js, test/containers/Main.spec.js, test/controllers/account.controller.spec.js, test/components/competitor-report/CompetitorReportComponent.spec.js], rss=315117568, heapTotal=289101856, heapUsed=261299120, loadavg=[2.87158203125, 2.1533203125, 1.97314453125], uptime=4056405, trace=[column=19, 
file={...}/node_modules/enquire.js/dist/enquire.js, function=Object.MediaQueryDispatch, line=226, method=MediaQueryDispatch, native=false, column=9, file={...}/web/node_modules/enquire.js/dist/enquire.js, function=null, line=291, method=null, native=false, column=20, file=/{...}/web/node_modules/enquire.js/dist/enquire.js, function=i, line=11, method=null, native=false, column=2, 
file={...}/web/node_modules/enquire.js/dist/enquire.js, function=, line=21, method=null, native=false, column=26, file=module.js, function=Module._compile, line=399, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=406, method=_extensions..js, native=false, column=7, 
file={...}/web/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=166, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=345, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=302, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=355, method=require, native=false, column=17, file=internal/module.js, function=require, line=13, method=null, native=false, column=28, 
file=/{...}/web/node_modules/react-responsive-mixin/index.js, function=, line=2, method=null, native=false, column=26, file=module.js, function=Module._compile, line=399, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=406, method=_extensions..js, native=false, column=7, 
file=/{...}/web/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=166, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=345, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=302, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=355, method=require, native=false, column=17, file=internal/module.js, function=require, line=13, method=null, native=false, column=29, 
file=/{...}/web/node_modules/react-slick/lib/slider.js, function=, line=19, method=null, native=false, column=26, file=module.js, function=Module._compile, line=399, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=406, method=_extensions..js, native=false, column=7, 
file=/{...}/web/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=166, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=345, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=302, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=355, method=require, native=false, column=17, file=internal/module.js, function=require, line=13, method=null, native=false, column=18, 
file=/{...}/web/node_modules/react-slick/lib/index.js, function=, line=3, method=null, native=false, column=26, file=module.js, function=Module._compile, line=399, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=406, method=_extensions..js, native=false, column=7, 
file=/{...}/web/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=166, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=345, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=302, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=355, method=require, native=false, column=17, file=internal/module.js, function=require, line=13, method=null, native=false, column=1, file=CompetitorReportComponent.js, function=, line=3, method=null, native=false, column=26, file=module.js, function=Module._compile, line=399, method=_compile, native=false, column=5, 
file=/{...}/web/node_modules/babel-register/lib/node.js, function=loader, line=158, method=null, native=false, column=7, 
file=/{...}/web/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=168, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=345, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=302, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=355, method=require, native=false, column=17, file=internal/module.js, function=require, line=13, method=null, native=false, column=1, file=CompetitorReportComponent.spec.js, function=, line=5, method=null, native=false, column=26, file=module.js, function=Module._compile, line=399, method=_compile, native=false, column=5, 
file=/{...}/web/node_modules/babel-register/lib/node.js, function=loader, line=158, method=null, native=false, column=7, 
file=/{...}/web/node_modules/babel-register/lib/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=168, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=345, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=302, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=355, method=require, native=false, column=17, file=internal/module.js, function=require, line=13, method=null, native=false, column=27, 
file=/{...}/web/node_modules/mocha/lib/mocha.js, function=null, line=219, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=14, 
file=/{...}/web/node_modules/mocha/lib/mocha.js, function=Mocha.loadFiles, line=216, method=loadFiles, native=false, column=10, file=/{...}/web/node_modules/mocha/lib/mocha.js, function=Mocha.run, line=468, method=run, native=false, column=18, 
file=/{...}/web/node_modules/mocha/bin/_mocha, function=, line=403, method=null, native=false, column=26, file=module.js, function=Module._compile, line=399, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=406, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=345, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=302, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain, line=431, method=Module.runMain, native=false, column=18, file=node.js, function=startup, line=141, method=null, native=false, column=3, file=node.js, function=null, line=977, method=null, native=false], stack=[Error: matchMedia not present, legacy browsers require a polyfill,     at Object.MediaQueryDispatch 
(/{...}/web/node_modules/enquire.js/dist/enquire.js:226:19),     at /{...}/web/node_modules/enquire.js/dist/enquire.js:291:9,     at i (/{...}/web/node_modules/enquire.js/dist/enquire.js:11:20),     at Object.<anonymous> 
(/{...}/web/node_modules/enquire.js/dist/enquire.js:21:2),     at Module._compile (module.js:399:26),     at Module._extensions..js (module.js:406:10),     at Object.require.extensions.(anonymous function) [as .js] 
(/{...}/web/node_modules/babel-register/lib/node.js:166:7),     at Module.load (module.js:345:32),     at Function.Module._load (module.js:302:12),     at Module.require (module.js:355:17),     at require (internal/module.js:13:17),     at Object.<anonymous> (/{...}/web/node_modules/react-responsive-mixin/index.js:2:28),     at Module._compile (module.js:399:26),     at Module._extensions..js (module.js:406:10),     at Object.require.extensions.(anonymous function) [as .js] 
(/{...}/web/node_modules/babel-register/lib/node.js:166:7),     at Module.load (module.js:345:32),     at Function.Module._load (module.js:302:12),     at Module.require (module.js:355:17),     at require (internal/module.js:13:17),     at Object.<anonymous> (/{...}/web/node_modules/react-slick/lib/slider.js:19:29),     at Module._compile (module.js:399:26),     at Module._extensions..js (module.js:406:10),     at Object.require.extensions.(anonymous function) [as .js] 
({...}/web/node_modules/babel-register/lib/node.js:166:7),     at Module.load (module.js:345:32),     at Function.Module._load (module.js:302:12),     at Module.require (module.js:355:17),     at require (internal/module.js:13:17),     at Object.<anonymous> ({...}/node_modules/react-slick/lib/index.js:3:18),     at Module._compile (module.js:399:26),     at Module._extensions..js (module.js:406:10),     at Object.require.extensions.(anonymous function) [as .js] 
({...}/node_modules/babel-register/lib/node.js:166:7),     at Module.load (module.js:345:32),     at Function.Module._load (module.js:302:12),     at Module.require (module.js:355:17),     at require (internal/module.js:13:17),     at Object.<anonymous> (CompetitorReportComponent.js:3:1),     at Module._compile (module.js:399:26),     at loader (/{...}/web/node_modules/babel-register/lib/node.js:158:5),     at Object.require.extensions.(anonymous function) [as .js] 
({...}/node_modules/babel-register/lib/node.js:168:7),     at Module.load (module.js:345:32),     at Function.Module._load (module.js:302:12),     at Module.require (module.js:355:17),     at require (internal/module.js:13:17),     at Object.<anonymous> (CompetitorReportComponent.spec.js:5:1),     at Module._compile (module.js:399:26),     at loader ({...}/node_modules/babel-register/lib/node.js:158:5),     at Object.require.extensions.(anonymous function) [as .js] 
({...}/node_modules/babel-register/lib/node.js:168:7),     at Module.load (module.js:345:32),     at Function.Module._load (module.js:302:12),     at Module.require (module.js:355:17),     at require (internal/module.js:13:17),     at /{...}/node_modules/mocha/lib/mocha.js:219:27,     at Array.forEach (native),     at Mocha.loadFiles 
({...}/node_modules/mocha/lib/mocha.js:216:14),     at Mocha.run (/{...}/web/node_modules/mocha/lib/mocha.js:468:10),     at Object.<anonymous> 
({...}/node_modules/mocha/bin/_mocha:403:18),     at Module._compile (module.js:399:26),     at Object.Module._extensions..js (module.js:406:10),     at Module.load (module.js:345:32),     at Function.Module._load (module.js:302:12),     at Function.Module.runMain (module.js:431:10),     at startup (node.js:141:18),     at node.js:977:3]
```

All test suites for all files fail to initiate as a result. If anyone has any suggestions, please let me know, thanks!

**Comment by chrishinrichs** [comment] 2016-07-01 18:29
+1

**Comment by psimyn** [comment] 2016-07-04 03:22
Duplicate of https://github.com/akiran/react-slick/issues/93

You can stub it out, shown in this comment 
https://github.com/WickyNilliams/enquire.js/issues/82#issuecomment-26990494

**Closed** 2016-08-14 11:44 UTC

**Comment by ettaibi** [comment] 2016-12-29 23:10
can you please explain what does stub out mean, should i change enquire.js file to the code given in the comment ? because my gitlab tests will fail if so

**Comment by psimyn** [comment] 2016-12-30 00:54
stubbing means adding fake matchMedia functions that don't do anything. Where you'll put it depends on how your tests are set up (e.g using jsdom or real browser). There should be a `beforeAll` or `beforeEach` hook where you can run code globally for the test environment

Otherwise, if you add code similar to what I linked above then it could just go somewhere in your app - this will use matchMedia if it exists otherwise use our stubbed version

```
window.matchMedia = window.matchMedia || function() {
    return {
        matches : false,
        addListener : function() {},
        removeListener: function() {}
    };
};
```
