### ISSUE TITLE
Slider freezes after adding and removing items

### ISSUE THREAD

**Issue by Pave91** [akiran/react-slick#140] opened 2015-10-08 09:36 UTC
When I  manipulate with items (add or remove items many times) through state (I have own state for items) and meanwhile user click on next arrow, carousel freezes and it's not possible to move slider back or forward. I load next items through ajax.

**Comment by nutank** [comment] 2015-10-08 14:28
I am facing the same issue. If the browser is kept open for long and if we get back to the same page, the slider freezes and its not possible to move between slides

**Comment by danielbuechele** [comment] 2015-10-08 15:40
For me, this happens when clicking on the next/prev arrow while another slide transition is running. I am not changing the contents of the slider.

**Comment by danielbuechele** [comment] 2015-10-15 09:44
What I found out is. The slider freezing is caused by `this.state.animation` on `InnerSlider` not being set back to `false`. However, I didn't found a fix for this yet. To me it looks like some kind of concurrency problem where e.g. the callback that should set `animating` to `false` is fired to early.

**Comment by akiran** [comment] 2015-10-15 09:49
Thanks for digging into the issue.
I will try to fix it today

**Comment by Pave91** [comment] 2015-10-15 11:48
Perfect! Thank you guys.

**Comment by akiran** [comment] 2015-10-20 16:24
Added fix proposed by @danielbuechele and released 0.8.1
@Pave91  @nutank  Please check if it solves your problem.

**Comment by danielbuechele** [comment] 2015-10-21 03:52
I think you need to also remove the lock from this part (https://github.com/digitalegarage/react-slick/commit/a5fe2a75bf8535157cc901bbc148932288b71460) Also I am wondering what the lock was for in the first place and if it makes sense to remove it completely or would something break if it is removed?

**Comment by Pave91** [comment] 2015-10-21 08:23
SItuation is better now, but still in some situations carousel freezes. I'm wondering the same thing like @danielbuechele .

**Comment by jjalonso** [comment] 2015-10-26 03:24
setting a state prop on beforeSlider event, that dont have nothing to do with the slider. also frezee it.

**Comment by mmmurf** [comment] 2015-11-30 20:03
this appears to not be fixed as of 0.9.2

**Closed** 2016-01-19 08:31 UTC
