### ISSUE TITLE
Implementation of FocusOnSelect

### ISSUE THREAD

**Issue by pavanmehta91** [akiran/react-slick#349] opened 2016-07-04 09:48 UTC
I want to implement FocusOnSelect for my use in react-slick. Can anybody guide me through this.
I'd used the method to update the state var onActive and apply css accordingly. It goes work but at times it makes the slick slider stop and it stops sliding.
![myslick](https://cloud.githubusercontent.com/assets/10721301/16556932/6ba3fd42-41fa-11e6-8fa8-c95c1804caa1.jpg)

**Comment by akiran** [comment] 2016-08-14 11:59
duplicate of #336

**Closed by akiran** 2016-08-14 11:59 UTC
