### ISSUE TITLE
React loading twice

### ISSUE THREAD

**Issue by sudarshanb1988** [akiran/react-slick#435] opened 2016-08-25 05:17 UTC
Whenever I try to use react slick I see this error on console: 
_invariant.js:38Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner)_
I tried removing node_modules and doing a fresh npm install. No luck :(

**Comment by akiran** [comment] 2016-08-25 06:05
Which version of react are you using ?

**Comment by sudarshanb1988** [comment] 2016-08-25 06:21
@akiran react@15.0.1 and react-dom@15.0.1

**Comment by IRT-fbachmann** [comment] 2016-08-25 08:51
Had a similar problem on Monday. Try and look for duplicates of React with different version:
`npm ls | grep react`

After that, just delete `node_modules` and `npm install` again. Help me in an instance after long seeking for a solution...

**Comment by akiran** [comment] 2016-08-25 09:51
If your are using webpack,  try dedupe plugin to avoid duplicates
https://webpack.github.io/docs/list-of-plugins.html#dedupeplugin

**Comment by sudarshanb1988** [comment] 2016-08-25 12:20
We are using browserify and It worked with browserify-resolutions package _browserify(options).plugin(resolutions, '*')_

**Comment by akiran** [comment] 2016-08-25 14:46
Closing this since the issue is solved

**Closed by akiran** 2016-08-25 14:46 UTC
