### ISSUE TITLE
initialSlide not working

### ISSUE THREAD

**Issue by gkrinc** [akiran/react-slick#325] opened 2016-06-07 18:35 UTC
With the follow setup you can see that the image in slide 1 isn't being displayed, and the slider is in the wrong position. As soon as you start moving the carousel, the image is slide 1 is displayed and the carousel jumps to the correct position:

[https://jsfiddle.net/6a98owdb/](https://jsfiddle.net/6a98owdb/)

It seems like something isn't being calculated correctly when the carousel is initialized like the image hasn't been loaded so the carousel doesn't know the width...something along those lines. If you click run again on the fiddle the behaviour is slightly different; possibly because the images are cached.

I can remedy the issue by adding this code to my component that's loading the react-slick carousel, but this obviously isn't ideal:

```
componentDidMount() {
        var self = this;
        setTimeout(function(){
            self.forceUpdate();
        }, 100);
    },
```

**Comment by Themandunord** [comment] 2016-06-24 18:48
+1

**Comment by patotoma** [comment] 2016-06-30 11:56
+1

**Comment by jvmartins** [comment] 2016-07-05 09:22
+1

**Comment by akiran** [comment] 2016-08-14 12:10
This is the problem with centerMode and variableWidth, not intial slide
Duplicate of #357

**Closed by akiran** 2016-08-14 12:10 UTC

**Comment by rickyrauch** [comment] 2016-10-21 03:43
@gkrinc Thanks 👍
