### ISSUE TITLE
Extra div inside every single slide in react

### ISSUE THREAD

**Issue by foridpathan** [akiran/react-slick#2131] opened 2022-02-12 08:08 UTC
When I use just react Libary on HTML, CSS there not have an extra div but I fount an extra dive in react. Can you help me, please?

`
<div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 153px;">
  <div>
    <div class="step" style="width: 100%; display: inline-block;">
      <h3>1</h3>
    </div>
  </div>
</div>
`

**Comment by foridpathan** [comment] 2022-02-12 08:09
`
<div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 153px;">
  <div>
    <div class="step" style="width: 100%; display: inline-block;">
      <h3>1</h3>
    </div>
  </div>
</div>
`

**Comment by ardok** [comment] 2023-01-04 22:33
Need to get rid of this extra div as well. It's messing up with screen reader focus. As in, it adds unnecessary focus.

**Comment by eyupkoc29** [comment] 2023-03-28 21:59
It puts an extra div so it doesn't have a full height value. How to remove this extra div?

**Comment by akiran** [comment] 2024-01-19 07:52
duplicate of #1877

**Closed by akiran** 2024-01-19 07:52 UTC
