### ISSUE TITLE
focusOnSelect + infinite = going to last = goes wrong way

### ISSUE THREAD

**Issue by bradennapier** [akiran/react-slick#518] opened 2016-10-21 04:11 UTC
When using focusOnSelect and infinite mode & center mode I am having a weird effect.  If i click on the previous slide (9) when it starts up it scrolls far to the right rather than simply going to the left one making for a rather ugly transition.  Perhaps I am doing something incorrectly of course!

![image](https://cloud.githubusercontent.com/assets/15365418/19586459/d3a6a048-9709-11e6-9769-ffd5839327e6.png)

So in this example when I click "One!" it will scroll all the way to the left rather than simply moving one to the right.

**Comment by mschmidt712** [comment] 2016-11-01 18:24
This issue is happening for me as well. 

Expected behavior: 'focusOnSelect' performs same action with same animations as arrow click.
Actual behavior: 'focusOnSelect' cannot loop from first to last and vice versa.

Here is a fiddle that demonstrates the problem:
https://jsfiddle.net/mschmidt712/oqaLv6yy/3/

**Comment by RaphaelYan** [comment] 2017-03-17 16:49
Just happened to me so I made this fix : https://github.com/akiran/react-slick/pull/673

**Comment by laveesingh** [comment] 2018-02-19 11:22
The issue is fixed now: 421dc8cb10183ce18eeaa5d2edded87a2eeb3022

**Closed by laveesingh** 2018-02-19 11:22 UTC
