### ISSUE TITLE
Weird Div being output

### ISSUE THREAD

**Issue by saltnpixels** [akiran/react-slick#2297] opened 2023-10-26 20:49 UTC
There seems to be an extra div that surround each slide that is not in my code. So this package is creating it. It's ruining the ability to add spacing and other such css properties directly to the slide items. 

How can I remove that extra div directly inside slick-slide? It should not be there.
<img width="430" alt="Screenshot 2023-10-26 at 4 48 26 PM" src="https://github.com/akiran/react-slick/assets/11615474/a14039cc-160c-4d7e-b93a-6a22c6e5b71b">

**Comment by akiran** [comment] 2024-01-19 07:52
duplicate of #1877

**Closed by akiran** 2024-01-19 07:52 UTC
