### ISSUE TITLE
Bug with variableWidth and centerMode

### ISSUE THREAD

**Issue by bratva** [akiran/react-slick#357] opened 2016-07-13 11:23 UTC
Hello!

I have slider with this options

```
var options = {
        infinite: false,
        variableWidth: true,
        centerMode: true
}
```

When i swipe last slide to left or first slide to right, the slider throw error `Cannot read property 'offsetWidth' of undefined`; in `getTrackLeft`

Demo https://jsfiddle.net/t1ovuve8/

**Comment by chrishinrichs** [comment] 2016-08-02 00:44
+1

**Comment by nluck** [comment] 2016-10-26 23:27
+1

**Comment by maximusnikulin** [comment] 2017-01-17 04:45
+1

**Comment by roman-yakobnyuk** [comment] 2017-01-23 01:03
Same here, it also occurs without infinite mode enabled, with just center mode.

**Comment by chrishinrichs** [comment] 2017-01-24 18:26
Might want to give https://github.com/godaddy/react-img-carousel a try

**Comment by pjjanak** [comment] 2017-04-18 15:53
@akiran - Has there been any movement on this? I'm experiencing a similar issue with variableMode = true and setting an intialSlide. Namely, the initial slide isn't brought into frame. Forcing an update after the component mounts makes it a little better, but the initial slide is still a little bit off.

It seems like you closed #325 which describes my issue marking it as a duplicate of this.

**Comment by laveesingh** [comment] 2018-03-07 11:02
Similar issues have been fixed in previous releases, please try the latest version. If the issue still persists for you, please create a codesandbox demo and reopen it.

**Closed by laveesingh** 2018-03-07 11:02 UTC

**Comment by josephdonnelly** [comment] 2018-03-27 18:48
Unfortunately this issue still exists:
https://codesandbox.io/s/7m0qow8l9j

**Comment by laveesingh** [comment] 2018-03-28 07:11
The referenced commit should do it.
