### ISSUE TITLE
variableWidth: true + centerMode: true + infinite: true generates wrong starting slide

### ISSUE THREAD

**Issue by ruslansavenok** [akiran/react-slick#665] opened 2017-03-09 13:56 UTC
With this demo -> https://jsfiddle.net/yomygqqd/

Starting slide is -3, if u will use prev/next arrow, it will produce wrong scroll effects.

Same example with jquery slick.js -> https://jsbin.com/yokegajama/edit?html,css,output

**Comment by renatorib** [comment] 2017-03-13 18:40
Same issue here!

**Comment by NullDivision** [comment] 2017-03-14 07:26
I'm looking at your examples and both seem to be working. Is it still happening on your end? And if yes, on what browser?

**Comment by renatorib** [comment] 2017-03-14 18:45
@NullDivision 
![image](https://cloud.githubusercontent.com/assets/3277185/23917124/1cb6b644-08cd-11e7-9be9-43f46455dafe.png)

Wrong behavior, considering that it should be infinite.

**Comment by ruslansavenok** [comment] 2017-03-14 19:21
http://www.giphy.com/gifs/l0IxZYS2yQ8bMJmPm - this is behaviour on mac os chrome v56.

Slider is infinite, but starting slide is -2 instead of 0, when i click next button, it animates from -2 to 1.

I Also tested it on different resolutions, on some it works correctly, on some not.

With example in my demo, .slick-slider of 589px does produce this bug, but 635px does not.

**Comment by MindRave** [comment] 2017-03-16 18:27
Seeing the same problem here, although just with variableWidth + infinite. If I remove infinite, it works as it should.

**Comment by renatorib** [comment] 2017-03-17 14:07
I think the problem is in infinite and integrating it with other behaviors

**Comment by march08** [comment] 2018-01-29 13:25
Has this been solved? Have the same problem.

Having infinite, center is ok, there are problems when I am adding variableWidth: true

**Comment by laveesingh** [comment] 2018-03-28 11:19
Similar issues have been fixed in previous releases. Please feel free to request reopen if disagree.

**Closed by laveesingh** 2018-03-28 11:19 UTC
