### ISSUE TITLE
Freeze autoplay carousel in Demo page

### ISSUE THREAD

**Issue by kuy** [akiran/react-slick#169] opened 2015-11-09 09:25 UTC
I didn't dig this issue why it occurred, but I'd like to report and note steps to reproduce.

*Steps to reproduce*

1. Open [Demos](http://webrafter.com/opensource/react-slick) page in Chrome
1. Scroll down to Autoplay carousel
1. Keep Demos tab, and switch to other Chrome's tab
1. Wait 5 minutes
1. Back to Demos tab
1. Autoplay carousel is stopped

**Comment by laxplaer** [comment] 2015-11-10 07:44
+1

**Comment by donaldparker** [comment] 2015-11-20 22:18
+1

**Comment by jessy1092** [comment] 2015-12-17 15:35
Hi all, I create PR #199 for it. :)

**Comment by Cunha44** [comment] 2016-01-12 18:09
+1

**Comment by akiran** [comment] 2016-02-22 15:10
duplicate of #202

**Closed by akiran** 2016-02-22 15:10 UTC
