### ISSUE TITLE
Handling with CSS Modules - react-slick in gatsby project 

### ISSUE THREAD

**Issue by flavioalves** [akiran/react-slick#1018] opened 2018-02-17 20:49 UTC
Hey guys!

I'm using react-slick in gatsby project.  I'm trying to customize the "slick-current" but I couldn't because Gatsby use a CSS Module approach.

Do we have some work around to do it? Any suggestion?

Thanks!

**Comment by laveesingh** [comment] 2018-02-19 05:28
What is it that you're doing to customize?

**Comment by silicakes** [comment] 2018-02-20 15:53
@flavioalves 

1. Create a container for your slider, and position it appropriately.
You may want to take a look at `centerMode` and `centerPadding` for some alignments.
2. You can identify the current item with several methods. the clearest one is to bind a callback on `afterChange` and update your state from there:
#### configuration
```
afterChange: (index) => {
  this.setState({currentSlide: index});
}
```

#### slider
```
<Slider>
  {yourItems.map((item, index) => {
    return <item className={`${index === this.currentSlide ? "activeClass": ""}`}
  })}
</Slider>
```

3. `afterChange` can take care of your animations as well - just create your images with the corresponding indices and animate it  by either adding a class or calling an animation function on it:

#### render
```
render() {

return (<div>
    <div className="image-container">
       {yourImages.map((img, index) => {
          return <div className={this.state.currentSlide === index ? "animate": ""}>...</div>
        })}
    </div>
    <Slider>...</Slider>
  </div>)
}
```

**Comment by laveesingh** [comment] 2018-02-21 04:47
I presume the problem is solved, so I'm closing the issue.

**Closed by laveesingh** 2018-02-21 04:47 UTC
