### ISSUE TITLE
error `currentSlide` increased in deactive window

### ISSUE THREAD

**Issue by soulwu** [akiran/react-slick#179] opened 2015-11-25 08:22 UTC
with props
```js
{
  infinite: true,
  autoplay: true,
  useCSS: true
}
```

helper will run `autoplay` by `setTimeout` and increase the `currentSlide` state
but when I deactivate the window and turn it into background, css transition won't run, and no transitionEnd event triggered.

[helpers.js#L252](/akiran/react-slick/blob/0.9.2/src/mixins/helpers.js#L252) would increase the currentSlide but can't adjust to corrent index [helper.js#L204](/akiran/react-slick/blob/0.9.2/src/mixins/helpers.js#L204)

when I activate the window later, `currentSlide` already became a very large number, but only adjust by step [helpers.js#L144](/akiran/react-slick/blob/0.9.2/src/mixins/helpers.js#L144)

I fixed this issue by change [helpers.js#L144](/akiran/react-slick/blob/0.9.2/src/mixins/helpers.js#L144) to
```js
currentSlide = targetSlide % this.state.slideCount;
```

that's enough, but I suggest to put invoke of `autoplay()` inside animation callback

**Comment by vdv73rus** [comment] 2016-01-28 09:38
When this PR will be merged? I need this!

**Comment by artempartos** [comment] 2016-02-01 14:09
Need this PR too!

**Comment by akiran** [comment] 2016-02-22 15:12
Duplicate of #202

**Closed by akiran** 2016-02-22 15:12 UTC
