### ISSUE TITLE
Inactivity cause slides to disappear

### ISSUE THREAD

**Issue by konoufo** [akiran/react-slick#202] opened 2015-12-22 00:23 UTC
Whenever you don't interact with the slider for like 15 seconds, slides disappear. The arrow are still there even the dots, but no slide. And clicking on the arrows has absolutely no effect. Clicking on the dots though instantly make the corresponding slides appear. I have autoplay enabled.
![noslides](https://cloud.githubusercontent.com/assets/9636748/11944929/42c31e84-a818-11e5-989f-a4ca9f95911f.png)

**Comment by lancehub** [comment] 2015-12-22 16:11
I have same problem, and I find the fix, I will submit a PR soon.

**Comment by bingjie2680** [comment] 2016-01-02 17:01
The same problem here. But the fix posted above has a side effect that it does not auto play anymore.

**Comment by lancehub** [comment] 2016-01-05 11:05
@bingjie2680 I use auto play too, it works with this fix, can you describe more on the problem you met?

**Comment by madsobel** [comment] 2016-01-08 14:05
I've run into the same issue. Will test out your PL next week to see if it works

**Comment by madsobel** [comment] 2016-01-11 10:25
I can confirm that this is solved in #204

**Comment by madsobel** [comment] 2016-01-11 11:13
I can confirm that #204 works for Firefox, however it does not seem to work for Chrome?

**Comment by lancehub** [comment] 2016-01-11 11:24
I tested on chrome myself, I works.

**Comment by madsobel** [comment] 2016-01-25 14:06
Since this was reverted in https://github.com/akiran/react-slick/pull/220 - Can we then re-open this issue?

**Comment by akiran** [comment] 2016-02-26 05:06
This issue is fixed in react-slick@0.11
Can you test it  and le me know if it works for you

**Closed by akiran** 2016-02-26 05:06 UTC
Labels: bug

**Comment by pipzpadilla** [comment] 2017-08-22 10:04
slider is freezing once i scroll down the page in mobile
any solution for these?
