### ISSUE TITLE
bug in slick dots

### ISSUE THREAD

**Issue by sandeepsirodia** [akiran/react-slick#1523] opened 2019-03-27 14:46 UTC
hey when we switch swiping from slick dots to slick list or vice versa, it shows 2 slick dots activated ( black color )

**Comment by jaisonka91** [comment] 2019-04-11 05:37
In autoplay mode, if one dot is clicked by the user then it's showing as active always. So it will show two active dots.

**Comment by filip4428** [comment] 2019-05-10 13:14
I'm experiencing the same problem.

**Comment by akiran** [comment] 2019-07-13 11:18
Duplicate of #1432

**Closed by akiran** 2019-07-13 11:18 UTC
