### ISSUE TITLE
Text blurry in chrome when using "tranform:translate3d(x,y,z)"

### ISSUE THREAD

**Issue by HuiguangChu** [akiran/react-slick#94] opened 2015-08-04 12:21 UTC
could you change it to translateX for WebkitTransform like you did for msTransform?

**Comment by vramana** [comment] 2015-08-04 13:56
Shouldn't this be a bug in chrome? I am not sure how changing to translateX will solve your problem because they are literally same API except `translate3d` moves in two other directions. Have you tried this out? 

Which version of chrome are you using? Can you show a screenshots of using `translate3d` and `translateX`? Or just simply where you are having the blurry text? Why do you think its caused by `translate3d`?

**Comment by HuiguangChu** [comment] 2015-08-04 14:20
okay, you can compare two screenshots, one is using translateX and one is
using translate3d.
 Actually, translate3d cause text blurry in chrome is the common issue.


2015-08-04 15:56 GMT+02:00 Ramana Venkata <notifications@github.com>:

**Comment by vramana** [comment] 2015-08-04 14:27
Can you check if this works http://stackoverflow.com/a/7477166/1117168 ??

**Comment by HuiguangChu** [comment] 2015-08-04 14:31
thank you, i did that, it did not work. I don't get the point that why you are using 3d, as I can see you set  the y and z is 0. why you don't using translateX?, then you don't need to fix bug for IE as well

**Comment by vramana** [comment] 2015-08-04 14:58
I am slightly reluctant to do that because I want to know what exactly is the cause of problem and what is the best way to solve it. I am trying to read whatever I can find.

[This question](http://stackoverflow.com/questions/27385126/chrome-font-appears-blurry) states using `translateX` causes problems. According to [this reddit comment](https://www.reddit.com/r/web_design/comments/2z9ub7/css3_translatey_in_webkit_browsers_makes_text/cpgze9v), any type of transform can cause the blur. Sometimes the fixes work, sometimes they don't.

**Comment by vramana** [comment] 2015-08-04 15:07
@akiran How do you want to solve this?

**Comment by akiran** [comment] 2015-08-04 15:35
@HuiguangChu Original slick from which we ported this also uses translate3D 
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1696

**Comment by gtqnchev** [comment] 2016-08-17 13:34
I'm experiencing blurry text too. 
It seems to happen when non-integer values are given to translate3d.
Here is an example: [blurry](https://www.dropbox.com/s/yygbhe6n5kbr43t/Screenshot%202016-08-17%2016.14.05.png?dl=0),  [ok](https://www.dropbox.com/s/mcmo3tg376cu772/Screenshot%202016-08-17%2016.14.52.png?dl=0)

And it's happening only on safari and chrome, so it's mostly a webkit bug. But still maybe it can be fixed just by rounding the values. I've checked slick and it looks like it uses only integer values for translations and "slick-slide" width.

**Comment by akiran** [comment] 2016-08-17 14:39
@gtqnchev I will try rounding values passed to translate3d and see if this issue is fixed

**Comment by cjke** [comment] 2017-01-25 04:27
@akiran Was the rounded values feature pushed into master at all?

**Comment by edennington** [comment] 2017-05-10 00:21
@akiran looks like ghostd implemented a fix for rounding values. Any chance we can get this into master?

**Comment by svn1991** [comment] 2017-06-09 03:54
Hi @akiran 

Is there an update on whether this issue is fixed?

**Comment by cuquo** [comment] 2017-07-24 16:18
It's only happening in not-retina devices and when either X or Y final position it's not an integer, the above PR should fix that. Do you have any idea of when this will go into master? btw, thanks for porting this library.

**Comment by vinceprofeta** [comment] 2017-08-07 21:38
+1

**Comment by vinceprofeta** [comment] 2017-09-08 17:20
@akiran can you merge the PR

**Comment by evert-smit** [comment] 2017-11-20 20:16
Thanks for a great component!
I ran into this issue too, it would be nice if the fix could be merged.

**Comment by xxronis** [comment] 2017-11-30 12:10
+1

**Comment by ryangiglio** [comment] 2017-12-13 18:20
+1

**Comment by dsl-src** [comment] 2017-12-22 14:53
+1

**Comment by ruppalsingh** [comment] 2018-03-05 12:28
Has anyone tried the 0.19.0 release to see if e10e4fb fixed the issue for them?

**Comment by laveesingh** [comment] 2018-03-06 07:10
I can't regenerate the issue. And I don't think it exists anymore. If someone disagrees and the issue still persists for them, please feel free to create a codesandbox demo for the same and open the issue.

**Closed by laveesingh** 2018-03-06 07:10 UTC
