### ISSUE TITLE
React Slick blocked by AdBlock 

### ISSUE THREAD

**Issue by reinaldoferreira** [akiran/react-slick#1957] opened 2021-01-05 09:12 UTC
AdBlockers like uBlock, are hiding the `.slick-track` div.
![image](https://user-images.githubusercontent.com/8379196/103628095-6a965f00-4f36-11eb-80ba-d0855998d309.png)

It looks like ad blockers don't like the words `track` or `slick`. We could solve this issue by renaming this class.

The same issue was reported on the js version of this plugin. 
https://github.com/kenwheeler/slick/issues/4029

**Comment by emileber** [comment] 2021-01-05 17:14
I was looking into the API and there's no way to easily change the `className` right now.

**Comment by emileber** [comment] 2021-01-05 17:15
Seems like uBlock fixed this false positive filter: https://github.com/uBlockOrigin/uAssets/issues/8424

**Comment by akiran** [comment] 2021-01-10 07:33
Closing this as the issue is resolved

**Closed by akiran** 2021-01-10 07:33 UTC
