### ISSUE TITLE
Image carousel caught mid-swipe (mobile) or mid-drag (desktop)

### ISSUE THREAD

**Issue by rainesinternationaldev** [akiran/react-slick#585] opened 2016-12-22 20:17 UTC
I understand that this issue has been brought up in #162 and #412, but I'm not sure if it's been fully addressed. Images simply stop scrolling.

#### Initial page load:
<img width="608" alt="screen shot 2016-12-22 at 3 11 10 pm" src="https://cloud.githubusercontent.com/assets/21286106/21438955/82781130-c859-11e6-87c7-a9fa621a9b22.png">

####  Post-swipe:
<img width="606" alt="screen shot 2016-12-22 at 3 16 42 pm" src="https://cloud.githubusercontent.com/assets/21286106/21439001/ae194304-c859-11e6-9045-8eaea952b634.png">

####  Images continue to auto-fade in that position:
<img width="603" alt="screen shot 2016-12-22 at 3 16 45 pm" src="https://cloud.githubusercontent.com/assets/21286106/21439011/b6015bc4-c859-11e6-8b18-b1256e2162da.png">

Settings:
```
{
      dots: true,
      infinite: true,
      fade: true,
      speed: 1000,
      slidesToShow: 1,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 5000,
      arrows: false,
      draggable: true,
      swipe: true,
      swipeToSlide: true
};
```
Version: `v0.14.5`

**Comment by coreyleelarson** [comment] 2017-01-10 23:35
We are having the same issue. We suspect it has something to do with "fade" and "swipe" both being enabled, but haven't come up with a solution.

**Comment by SrSandeepKumar** [comment] 2017-02-09 11:56
Facing similar issue once i zoom in on image and scroll.

**Comment by cgalbiati** [comment] 2017-03-22 15:20
Also having the same issue and pretty sure it is caused by fade and swipe together.

**Comment by laveesingh** [comment] 2018-02-05 10:38
Problems related to fade+swipe were solved in the previous release. I'm closing this for now. If someone still faces any issue similar to this, please feel free to open another one.

**Closed by laveesingh** 2018-02-05 10:38 UTC
