### ISSUE TITLE
combining non-infinite, centerMode, and variableWidth causes an error

### ISSUE THREAD

**Issue by nagolyhprum** [akiran/react-slick#365] opened 2016-07-19 14:03 UTC
https://jsfiddle.net/20bumb4g/906/

> var settings = {
>   infinite : false,
>   variableWidth: true,
>   centerMode: true
> }

this combination of settings causes an error when you attempt to go out of bounds

**Comment by akiran** [comment] 2016-08-14 11:37
Duplicate of #357

**Closed by akiran** 2016-08-14 11:37 UTC
