### ISSUE TITLE
errors in concurrent mode - > UNSAFE_componentWillMount

### ISSUE THREAD

**Issue by pejman1** [akiran/react-slick#1755] opened 2020-03-31 14:05 UTC
index.js:14426 Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: InnerSlider, Slider

index.js:14426 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: InnerSlider

**Comment by smorfe** [comment] 2020-04-04 01:36
I am having the same issue...

**Comment by paufar** [comment] 2020-04-04 03:12
same here would be good if this gets updated

**Comment by Aristod3mus** [comment] 2020-04-10 11:01
same problem

**Comment by moh3ni** [comment] 2020-04-13 12:08
same issue

**Comment by bijaybdrkarki** [comment] 2020-04-15 00:01
@akiran can you please have a look at the issue..?

**Comment by nickwlker** [comment] 2020-04-15 04:40
same issue

**Comment by olasunkanmi04** [comment] 2020-04-16 09:20
I have the same issue

**Comment by Jeconias** [comment] 2020-04-17 01:34
Same issue

**Comment by imparvez** [comment] 2020-04-18 10:42
@akiran facing the same issue. Can you please look into this issue and if any changes, then when are you planning to take it? Thanks

**Comment by tuguldur** [comment] 2020-04-19 03:42
```
ReactDOM.render(
  <React.StrictMode> 
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);
```
to 
```
ReactDOM.render(
    <App />,
  document.getElementById("root")
);
```

**Comment by pejman1** [comment] 2020-04-19 07:30
> ```
> ReactDOM.render(
>   <React.StrictMode> 
>     <App />
>   </React.StrictMode>,
>   document.getElementById("root")
> );
> ```
> 
> to
> 
> ```
> ReactDOM.render(
>     <App />,
>   document.getElementById("root")
> );
> ```

It doesn't solve the problem

**Comment by bijaybdrkarki** [comment] 2020-04-19 19:27
> ```
> ReactDOM.render(
>   <React.StrictMode> 
>     <App />
>   </React.StrictMode>,
>   document.getElementById("root")
> );
> ```
> 
> to
> 
> ```
> ReactDOM.render(
>     <App />,
>   document.getElementById("root")
> );
> ```

for me it solved the problem. thanks

**Comment by olasunkanmi04** [comment] 2020-04-19 19:30
> ```
> ReactDOM.render(
>   <React.StrictMode> 
>     <App />
>   </React.StrictMode>,
>   document.getElementById("root")
> );
> ```
> 
> to
> 
> ```
> ReactDOM.render(
>     <App />,
>   document.getElementById("root")
> );
> ```

This solved it for me. Thank you

**Comment by pejman1** [comment] 2020-04-19 20:40
> > ```
> > ReactDOM.render(
> >   <React.StrictMode> 
> >     <App />
> >   </React.StrictMode>,
> >   document.getElementById("root")
> > );
> > ```
> > 
> > 
> > to
> > ```
> > ReactDOM.render(
> >     <App />,
> >   document.getElementById("root")
> > );
> > ```
> 
> This solved it for me. Thank you

interesting ! for me the error is still there

**Comment by paufar** [comment] 2020-04-22 23:39
@akiran do you think you will fix this issue please?

**Comment by ajj-siraj** [comment] 2020-05-11 01:19
> ```
> ReactDOM.render(
>   <React.StrictMode> 
>     <App />
>   </React.StrictMode>,
>   document.getElementById("root")
> );
> ```
> 
> to
> 
> ```
> ReactDOM.render(
>     <App />,
>   document.getElementById("root")
> );
> ```

This works but you're not changing anything except removing the error message and all the benefits of the strict mode.
The comp still needs to be updated.

**Comment by mactung** [comment] 2020-05-28 05:35
i have problem too anyone can fix it

**Comment by Alekseyideas** [comment] 2020-05-28 07:42
> i have problem too anyone can fix it

delete <React.StrictMode> until they update react-slick with fixes

**Comment by RomanistHere** [comment] 2020-07-07 14:39
How could this be most popular library for react and you have to disable strict mode to run it?

**Comment by andocodes** [comment] 2020-08-14 19:39
Following this. It's not a complete gamebreaking change but would be nice to get rid of this. Looks like we need to swap out the unsafe componentWillReceiveProps React method. @akiran thoughts/how far have we got with this?

**Comment by akiran** [comment] 2020-08-15 11:54
@andocodes I am working on it. Hopefully, I will make a release next week with a fix for this

**Comment by akiran** [comment] 2020-08-16 18:34
@andocodes @Alekseyideas @mactung @paufar @pejman1 @smorfe @moh3ni 
I release react-slick@0.27.9 with a fix for this.

Can you test it now?

**Comment by paufar** [comment] 2020-08-16 23:00
@akiran Confirmed from my end! Error is gone. Thankyou!

**Closed** 2020-08-17 06:14 UTC

**Comment by andocodes** [comment] 2020-08-17 11:35
@akiran just to also confirm - all gone now. Awesome work bud!

**Comment by a-statefull-mind** [comment] 2021-12-29 09:31
> ```
> ReactDOM.render(
>   <React.StrictMode> 
>     <App />
>   </React.StrictMode>,
>   document.getElementById("root")
> );
> ```
> 
> to
> 
> ```
> ReactDOM.render(
>     <App />,
>   document.getElementById("root")
> );
> ```

is not the solution.

**Comment by cassianomon** [comment] 2022-01-05 17:39
> @andocodes @Alekseyideas @mactung @paufar @pejman1 @smorfe @moh3ni I release react-slick@0.27.9 with a fix for this.
> 
> Can you test it now?

@akiran it fixes but then it brings back another bug: When reloading the page in responsive mode, the first slide is empty.
