### ISSUE TITLE
Slider completely stops working when re-rendering multiple times

### ISSUE THREAD

**Issue by mkralla11** [akiran/react-slick#337] opened 2016-06-17 19:59 UTC
After rendering multiple times, even if no settings were changes for the react-slick slider, the slider completely stops working. No button clicks, no swipes work, and the slider is completely stopped. Here is the problem occuring:

https://jsfiddle.net/20bumb4g/727/

To reproduce, click the next and/or previous buttons until you notice that nothing is working anymore. All the code is doing is re-rendering the given component about every second.

Expected when rerendering:
The react-slider show continue working, including all buttons.

Actual Result:
The react-slider stops sliding and no buttons work anymore.

**Comment by maxfriedmann** [comment] 2016-06-21 12:40
I get the same result when I update a component while the slide animation is being done. In one of my projects I have some translated text on a sliding box, when I change the language while it is sliding, it stops sliding and the buttons don't work anymore. 

Maybe this is the same error?

Your Fiddle doesn't work anymore unfortunately...

**Comment by mkralla11** [comment] 2016-06-22 13:54
Do you mean the fiddle doesn't load or you can't actually use the slider in the fiddle? Anyways, I'm pretty sure you're having the same issue, as soon as you setState a few times on any parent component or the given slider wrapper component itself, all slider functionality breaks: no sliding, no buttons work. I recently switched to https://github.com/kenwheeler/nuka-carousel but that slider has it's own set of issues...I can't recommend it.

**Comment by vemperor** [comment] 2016-07-08 14:11
Yep, same here in chrome/safary (no problem in ff). It looks like callbacks "disappear" after rerender while scrolling and `animating` don't go to `false`. Don't know if that's expected behavior. Any ideas?

**Comment by vemperor** [comment] 2016-07-08 14:37
also, jsfiddle: https://jsfiddle.net/2gybogg4/1/

**Comment by bergkampho** [comment] 2016-07-21 10:09
I found the same issues while resizing the screen when the slide is animating.
The state `animating` keep in `true` and doesn't go to `false` after resize. It causes `slideHandler` always return.

**Comment by pelhage** [comment] 2016-08-04 22:43
I am having the same issue. When I update the children or re-render the slide stops working altogether

**Comment by grossmail1** [comment] 2016-08-04 22:46
Honestly, I just went to the standard slick implementation with Jquery. It felt dirty and wrong and was definitely a little tougher to implement. But it is far less buggy.

**Comment by pelhage** [comment] 2016-08-05 00:08
I have confirmed that the slideshow will break if it is re-rendered during an animation: https://jsfiddle.net/20bumb4g/1027/

If you click the "Trigger re-render button" you'll see that the slideshow breaks and is no longer functional

**Comment by dcocchia** [comment] 2016-08-11 04:34
This occurs frequently when multiple carousels exist on a page that all re-render based on a single data-source, like a Redux store.

**Comment by vemperor** [comment] 2016-08-11 07:06
I temporarily use [dirty hack to get react-slick go through rerenders](https://github.com/vemperor/react-slick/commit/bc570ce0709858424a011a8e7bb144a9376bfdfa). Hope it helps, though it's not a solution for the problem.

**Comment by dcocchia** [comment] 2016-08-11 18:33
I believe this will help with many issues here: https://github.com/akiran/react-slick/pull/407

@akiran please give this a look through. It essentially checks to see if the `ReactTransitionEvents` events triggered within a reasonable time (2x the speed set in the props). If it hasn't triggered, it's most likely because of a re-render due to state change during animation.

**Comment by mikkelwf** [comment] 2017-03-03 12:48
Is there any progress on this issue..?

**Comment by aakashrshah** [comment] 2017-06-17 12:08
Similar issue. Are there any updates or workarounds except from the ones mentioned above? Need help urgent.

**Comment by hypnagonia** [comment] 2017-08-09 14:47
Same problem

**Comment by noushad-pp** [comment] 2017-11-01 13:16
Same problem. Multiple sliders. All slidesrs stops working once I call a setState in one of the afterChange callbacks

**Comment by Venumteam** [comment] 2017-11-03 10:23
Also, this problem occurs after calling setState in the afterChange callback

**Comment by laveesingh** [comment] 2018-03-28 10:43
Such problems have been fixed in previous releases. Please feel free to request reopen if disagree.

**Closed by laveesingh** 2018-03-28 10:43 UTC

**Comment by zibuyu69** [comment] 2019-09-08 13:37
我在将 autoplay 设置为true然后变为false后再次遇到这个问题，表现为autoplay 再次接收到true也无法自动切换了。

**Comment by AposLaz** [comment] 2022-11-08 15:12
Same problem here
